name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        env:
          CYPRESS_SECRET_PASS: ${{ secrets.CYPRESS_SECRET_PASS }}
        run: "npx cypress run --spec cypress/e2e/test1/*"
